[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "The Psychology of Mindful Leadership for Women: Understanding the Unique Challenges and Opportunities of Women in Leadership and How to Use Mindfulness to Thrive"
